// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package kafkatest

import (
	"context"
	"github.com/ONSdigital/dp-kafka"
	"sync"
)

var (
	lockProducerMockChannels      sync.RWMutex
	lockProducerMockClose         sync.RWMutex
	lockProducerMockInitialise    sync.RWMutex
	lockProducerMockIsInitialised sync.RWMutex
)

// Ensure, that ProducerMock does implement Producer.
// If this is not the case, regenerate this file with moq.
var _ Producer = &ProducerMock{}

// ProducerMock is a mock implementation of Producer.
//
//     func TestSomethingThatUsesProducer(t *testing.T) {
//
//         // make and configure a mocked Producer
//         mockedProducer := &ProducerMock{
//             ChannelsFunc: func() *kafka.ProducerChannels {
// 	               panic("mock out the Channels method")
//             },
//             CloseFunc: func(ctx context.Context) error {
// 	               panic("mock out the Close method")
//             },
//             InitialiseFunc: func(ctx context.Context) error {
// 	               panic("mock out the Initialise method")
//             },
//             IsInitialisedFunc: func() bool {
// 	               panic("mock out the IsInitialised method")
//             },
//         }
//
//         // use mockedProducer in code that requires Producer
//         // and then make assertions.
//
//     }
type ProducerMock struct {
	// ChannelsFunc mocks the Channels method.
	ChannelsFunc func() *kafka.ProducerChannels

	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context) error

	// InitialiseFunc mocks the Initialise method.
	InitialiseFunc func(ctx context.Context) error

	// IsInitialisedFunc mocks the IsInitialised method.
	IsInitialisedFunc func() bool

	// calls tracks calls to the methods.
	calls struct {
		// Channels holds details about calls to the Channels method.
		Channels []struct {
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Initialise holds details about calls to the Initialise method.
		Initialise []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// IsInitialised holds details about calls to the IsInitialised method.
		IsInitialised []struct {
		}
	}
}

// Channels calls ChannelsFunc.
func (mock *ProducerMock) Channels() *kafka.ProducerChannels {
	if mock.ChannelsFunc == nil {
		panic("ProducerMock.ChannelsFunc: method is nil but Producer.Channels was just called")
	}
	callInfo := struct {
	}{}
	lockProducerMockChannels.Lock()
	mock.calls.Channels = append(mock.calls.Channels, callInfo)
	lockProducerMockChannels.Unlock()
	return mock.ChannelsFunc()
}

// ChannelsCalls gets all the calls that were made to Channels.
// Check the length with:
//     len(mockedProducer.ChannelsCalls())
func (mock *ProducerMock) ChannelsCalls() []struct {
} {
	var calls []struct {
	}
	lockProducerMockChannels.RLock()
	calls = mock.calls.Channels
	lockProducerMockChannels.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *ProducerMock) Close(ctx context.Context) error {
	if mock.CloseFunc == nil {
		panic("ProducerMock.CloseFunc: method is nil but Producer.Close was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockProducerMockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	lockProducerMockClose.Unlock()
	return mock.CloseFunc(ctx)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedProducer.CloseCalls())
func (mock *ProducerMock) CloseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockProducerMockClose.RLock()
	calls = mock.calls.Close
	lockProducerMockClose.RUnlock()
	return calls
}

// Initialise calls InitialiseFunc.
func (mock *ProducerMock) Initialise(ctx context.Context) error {
	if mock.InitialiseFunc == nil {
		panic("ProducerMock.InitialiseFunc: method is nil but Producer.Initialise was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockProducerMockInitialise.Lock()
	mock.calls.Initialise = append(mock.calls.Initialise, callInfo)
	lockProducerMockInitialise.Unlock()
	return mock.InitialiseFunc(ctx)
}

// InitialiseCalls gets all the calls that were made to Initialise.
// Check the length with:
//     len(mockedProducer.InitialiseCalls())
func (mock *ProducerMock) InitialiseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockProducerMockInitialise.RLock()
	calls = mock.calls.Initialise
	lockProducerMockInitialise.RUnlock()
	return calls
}

// IsInitialised calls IsInitialisedFunc.
func (mock *ProducerMock) IsInitialised() bool {
	if mock.IsInitialisedFunc == nil {
		panic("ProducerMock.IsInitialisedFunc: method is nil but Producer.IsInitialised was just called")
	}
	callInfo := struct {
	}{}
	lockProducerMockIsInitialised.Lock()
	mock.calls.IsInitialised = append(mock.calls.IsInitialised, callInfo)
	lockProducerMockIsInitialised.Unlock()
	return mock.IsInitialisedFunc()
}

// IsInitialisedCalls gets all the calls that were made to IsInitialised.
// Check the length with:
//     len(mockedProducer.IsInitialisedCalls())
func (mock *ProducerMock) IsInitialisedCalls() []struct {
} {
	var calls []struct {
	}
	lockProducerMockIsInitialised.RLock()
	calls = mock.calls.IsInitialised
	lockProducerMockIsInitialised.RUnlock()
	return calls
}
