// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package kafkatest

import (
	"github.com/ONSdigital/dp-kafka/v2"
	"sync"
)

var (
	lockMessageMockCommit           sync.RWMutex
	lockMessageMockCommitAndRelease sync.RWMutex
	lockMessageMockGetData          sync.RWMutex
	lockMessageMockMark             sync.RWMutex
	lockMessageMockOffset           sync.RWMutex
	lockMessageMockRelease          sync.RWMutex
	lockMessageMockUpstreamDone     sync.RWMutex
)

// Ensure, that MessageMock does implement kafka.Message.
// If this is not the case, regenerate this file with moq.
var _ kafka.Message = &MessageMock{}

// MessageMock is a mock implementation of kafka.Message.
//
//     func TestSomethingThatUsesMessage(t *testing.T) {
//
//         // make and configure a mocked kafka.Message
//         mockedMessage := &MessageMock{
//             CommitFunc: func()  {
// 	               panic("mock out the Commit method")
//             },
//             CommitAndReleaseFunc: func()  {
// 	               panic("mock out the CommitAndRelease method")
//             },
//             GetDataFunc: func() []byte {
// 	               panic("mock out the GetData method")
//             },
//             MarkFunc: func()  {
// 	               panic("mock out the Mark method")
//             },
//             OffsetFunc: func() int64 {
// 	               panic("mock out the Offset method")
//             },
//             ReleaseFunc: func()  {
// 	               panic("mock out the Release method")
//             },
//             UpstreamDoneFunc: func() chan struct{} {
// 	               panic("mock out the UpstreamDone method")
//             },
//         }
//
//         // use mockedMessage in code that requires kafka.Message
//         // and then make assertions.
//
//     }
type MessageMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func()

	// CommitAndReleaseFunc mocks the CommitAndRelease method.
	CommitAndReleaseFunc func()

	// GetDataFunc mocks the GetData method.
	GetDataFunc func() []byte

	// MarkFunc mocks the Mark method.
	MarkFunc func()

	// OffsetFunc mocks the Offset method.
	OffsetFunc func() int64

	// ReleaseFunc mocks the Release method.
	ReleaseFunc func()

	// UpstreamDoneFunc mocks the UpstreamDone method.
	UpstreamDoneFunc func() chan struct{}

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
		}
		// CommitAndRelease holds details about calls to the CommitAndRelease method.
		CommitAndRelease []struct {
		}
		// GetData holds details about calls to the GetData method.
		GetData []struct {
		}
		// Mark holds details about calls to the Mark method.
		Mark []struct {
		}
		// Offset holds details about calls to the Offset method.
		Offset []struct {
		}
		// Release holds details about calls to the Release method.
		Release []struct {
		}
		// UpstreamDone holds details about calls to the UpstreamDone method.
		UpstreamDone []struct {
		}
	}
}

// Commit calls CommitFunc.
func (mock *MessageMock) Commit() {
	if mock.CommitFunc == nil {
		panic("MessageMock.CommitFunc: method is nil but Message.Commit was just called")
	}
	callInfo := struct {
	}{}
	lockMessageMockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	lockMessageMockCommit.Unlock()
	mock.CommitFunc()
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//     len(mockedMessage.CommitCalls())
func (mock *MessageMock) CommitCalls() []struct {
} {
	var calls []struct {
	}
	lockMessageMockCommit.RLock()
	calls = mock.calls.Commit
	lockMessageMockCommit.RUnlock()
	return calls
}

// CommitAndRelease calls CommitAndReleaseFunc.
func (mock *MessageMock) CommitAndRelease() {
	if mock.CommitAndReleaseFunc == nil {
		panic("MessageMock.CommitAndReleaseFunc: method is nil but Message.CommitAndRelease was just called")
	}
	callInfo := struct {
	}{}
	lockMessageMockCommitAndRelease.Lock()
	mock.calls.CommitAndRelease = append(mock.calls.CommitAndRelease, callInfo)
	lockMessageMockCommitAndRelease.Unlock()
	mock.CommitAndReleaseFunc()
}

// CommitAndReleaseCalls gets all the calls that were made to CommitAndRelease.
// Check the length with:
//     len(mockedMessage.CommitAndReleaseCalls())
func (mock *MessageMock) CommitAndReleaseCalls() []struct {
} {
	var calls []struct {
	}
	lockMessageMockCommitAndRelease.RLock()
	calls = mock.calls.CommitAndRelease
	lockMessageMockCommitAndRelease.RUnlock()
	return calls
}

// GetData calls GetDataFunc.
func (mock *MessageMock) GetData() []byte {
	if mock.GetDataFunc == nil {
		panic("MessageMock.GetDataFunc: method is nil but Message.GetData was just called")
	}
	callInfo := struct {
	}{}
	lockMessageMockGetData.Lock()
	mock.calls.GetData = append(mock.calls.GetData, callInfo)
	lockMessageMockGetData.Unlock()
	return mock.GetDataFunc()
}

// GetDataCalls gets all the calls that were made to GetData.
// Check the length with:
//     len(mockedMessage.GetDataCalls())
func (mock *MessageMock) GetDataCalls() []struct {
} {
	var calls []struct {
	}
	lockMessageMockGetData.RLock()
	calls = mock.calls.GetData
	lockMessageMockGetData.RUnlock()
	return calls
}

// Mark calls MarkFunc.
func (mock *MessageMock) Mark() {
	if mock.MarkFunc == nil {
		panic("MessageMock.MarkFunc: method is nil but Message.Mark was just called")
	}
	callInfo := struct {
	}{}
	lockMessageMockMark.Lock()
	mock.calls.Mark = append(mock.calls.Mark, callInfo)
	lockMessageMockMark.Unlock()
	mock.MarkFunc()
}

// MarkCalls gets all the calls that were made to Mark.
// Check the length with:
//     len(mockedMessage.MarkCalls())
func (mock *MessageMock) MarkCalls() []struct {
} {
	var calls []struct {
	}
	lockMessageMockMark.RLock()
	calls = mock.calls.Mark
	lockMessageMockMark.RUnlock()
	return calls
}

// Offset calls OffsetFunc.
func (mock *MessageMock) Offset() int64 {
	if mock.OffsetFunc == nil {
		panic("MessageMock.OffsetFunc: method is nil but Message.Offset was just called")
	}
	callInfo := struct {
	}{}
	lockMessageMockOffset.Lock()
	mock.calls.Offset = append(mock.calls.Offset, callInfo)
	lockMessageMockOffset.Unlock()
	return mock.OffsetFunc()
}

// OffsetCalls gets all the calls that were made to Offset.
// Check the length with:
//     len(mockedMessage.OffsetCalls())
func (mock *MessageMock) OffsetCalls() []struct {
} {
	var calls []struct {
	}
	lockMessageMockOffset.RLock()
	calls = mock.calls.Offset
	lockMessageMockOffset.RUnlock()
	return calls
}

// Release calls ReleaseFunc.
func (mock *MessageMock) Release() {
	if mock.ReleaseFunc == nil {
		panic("MessageMock.ReleaseFunc: method is nil but Message.Release was just called")
	}
	callInfo := struct {
	}{}
	lockMessageMockRelease.Lock()
	mock.calls.Release = append(mock.calls.Release, callInfo)
	lockMessageMockRelease.Unlock()
	mock.ReleaseFunc()
}

// ReleaseCalls gets all the calls that were made to Release.
// Check the length with:
//     len(mockedMessage.ReleaseCalls())
func (mock *MessageMock) ReleaseCalls() []struct {
} {
	var calls []struct {
	}
	lockMessageMockRelease.RLock()
	calls = mock.calls.Release
	lockMessageMockRelease.RUnlock()
	return calls
}

// UpstreamDone calls UpstreamDoneFunc.
func (mock *MessageMock) UpstreamDone() chan struct{} {
	if mock.UpstreamDoneFunc == nil {
		panic("MessageMock.UpstreamDoneFunc: method is nil but Message.UpstreamDone was just called")
	}
	callInfo := struct {
	}{}
	lockMessageMockUpstreamDone.Lock()
	mock.calls.UpstreamDone = append(mock.calls.UpstreamDone, callInfo)
	lockMessageMockUpstreamDone.Unlock()
	return mock.UpstreamDoneFunc()
}

// UpstreamDoneCalls gets all the calls that were made to UpstreamDone.
// Check the length with:
//     len(mockedMessage.UpstreamDoneCalls())
func (mock *MessageMock) UpstreamDoneCalls() []struct {
} {
	var calls []struct {
	}
	lockMessageMockUpstreamDone.RLock()
	calls = mock.calls.UpstreamDone
	lockMessageMockUpstreamDone.RUnlock()
	return calls
}
