// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Shopify/sarama"
	"sync"
)

// SaramaConsumerGroupMock is a mock implementation of kafka.SaramaConsumerGroup.
//
// 	func TestSomethingThatUsesSaramaConsumerGroup(t *testing.T) {
//
// 		// make and configure a mocked kafka.SaramaConsumerGroup
// 		mockedSaramaConsumerGroup := &SaramaConsumerGroupMock{
// 			CloseFunc: func() error {
// 				panic("mock out the Close method")
// 			},
// 			ConsumeFunc: func(ctx context.Context, topics []string, handler sarama.ConsumerGroupHandler) error {
// 				panic("mock out the Consume method")
// 			},
// 			ErrorsFunc: func() <-chan error {
// 				panic("mock out the Errors method")
// 			},
// 		}
//
// 		// use mockedSaramaConsumerGroup in code that requires kafka.SaramaConsumerGroup
// 		// and then make assertions.
//
// 	}
type SaramaConsumerGroupMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// ConsumeFunc mocks the Consume method.
	ConsumeFunc func(ctx context.Context, topics []string, handler sarama.ConsumerGroupHandler) error

	// ErrorsFunc mocks the Errors method.
	ErrorsFunc func() <-chan error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Consume holds details about calls to the Consume method.
		Consume []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Topics is the topics argument value.
			Topics []string
			// Handler is the handler argument value.
			Handler sarama.ConsumerGroupHandler
		}
		// Errors holds details about calls to the Errors method.
		Errors []struct {
		}
	}
	lockClose   sync.RWMutex
	lockConsume sync.RWMutex
	lockErrors  sync.RWMutex
}

// Close calls CloseFunc.
func (mock *SaramaConsumerGroupMock) Close() error {
	if mock.CloseFunc == nil {
		panic("SaramaConsumerGroupMock.CloseFunc: method is nil but SaramaConsumerGroup.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedSaramaConsumerGroup.CloseCalls())
func (mock *SaramaConsumerGroupMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Consume calls ConsumeFunc.
func (mock *SaramaConsumerGroupMock) Consume(ctx context.Context, topics []string, handler sarama.ConsumerGroupHandler) error {
	if mock.ConsumeFunc == nil {
		panic("SaramaConsumerGroupMock.ConsumeFunc: method is nil but SaramaConsumerGroup.Consume was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Topics  []string
		Handler sarama.ConsumerGroupHandler
	}{
		Ctx:     ctx,
		Topics:  topics,
		Handler: handler,
	}
	mock.lockConsume.Lock()
	mock.calls.Consume = append(mock.calls.Consume, callInfo)
	mock.lockConsume.Unlock()
	return mock.ConsumeFunc(ctx, topics, handler)
}

// ConsumeCalls gets all the calls that were made to Consume.
// Check the length with:
//     len(mockedSaramaConsumerGroup.ConsumeCalls())
func (mock *SaramaConsumerGroupMock) ConsumeCalls() []struct {
	Ctx     context.Context
	Topics  []string
	Handler sarama.ConsumerGroupHandler
} {
	var calls []struct {
		Ctx     context.Context
		Topics  []string
		Handler sarama.ConsumerGroupHandler
	}
	mock.lockConsume.RLock()
	calls = mock.calls.Consume
	mock.lockConsume.RUnlock()
	return calls
}

// Errors calls ErrorsFunc.
func (mock *SaramaConsumerGroupMock) Errors() <-chan error {
	if mock.ErrorsFunc == nil {
		panic("SaramaConsumerGroupMock.ErrorsFunc: method is nil but SaramaConsumerGroup.Errors was just called")
	}
	callInfo := struct {
	}{}
	mock.lockErrors.Lock()
	mock.calls.Errors = append(mock.calls.Errors, callInfo)
	mock.lockErrors.Unlock()
	return mock.ErrorsFunc()
}

// ErrorsCalls gets all the calls that were made to Errors.
// Check the length with:
//     len(mockedSaramaConsumerGroup.ErrorsCalls())
func (mock *SaramaConsumerGroupMock) ErrorsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockErrors.RLock()
	calls = mock.calls.Errors
	mock.lockErrors.RUnlock()
	return calls
}
