// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/Shopify/sarama"
	"sync"
)

var (
	lockSaramaBrokerMockAddr        sync.RWMutex
	lockSaramaBrokerMockClose       sync.RWMutex
	lockSaramaBrokerMockConnected   sync.RWMutex
	lockSaramaBrokerMockGetMetadata sync.RWMutex
	lockSaramaBrokerMockOpen        sync.RWMutex
)

// SaramaBrokerMock is a mock implementation of kafka.SaramaBroker.
//
//     func TestSomethingThatUsesSaramaBroker(t *testing.T) {
//
//         // make and configure a mocked kafka.SaramaBroker
//         mockedSaramaBroker := &SaramaBrokerMock{
//             AddrFunc: func() string {
// 	               panic("mock out the Addr method")
//             },
//             CloseFunc: func() error {
// 	               panic("mock out the Close method")
//             },
//             ConnectedFunc: func() (bool, error) {
// 	               panic("mock out the Connected method")
//             },
//             GetMetadataFunc: func(request *sarama.MetadataRequest) (*sarama.MetadataResponse, error) {
// 	               panic("mock out the GetMetadata method")
//             },
//             OpenFunc: func(conf *sarama.Config) error {
// 	               panic("mock out the Open method")
//             },
//         }
//
//         // use mockedSaramaBroker in code that requires kafka.SaramaBroker
//         // and then make assertions.
//
//     }
type SaramaBrokerMock struct {
	// AddrFunc mocks the Addr method.
	AddrFunc func() string

	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// ConnectedFunc mocks the Connected method.
	ConnectedFunc func() (bool, error)

	// GetMetadataFunc mocks the GetMetadata method.
	GetMetadataFunc func(request *sarama.MetadataRequest) (*sarama.MetadataResponse, error)

	// OpenFunc mocks the Open method.
	OpenFunc func(conf *sarama.Config) error

	// calls tracks calls to the methods.
	calls struct {
		// Addr holds details about calls to the Addr method.
		Addr []struct {
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Connected holds details about calls to the Connected method.
		Connected []struct {
		}
		// GetMetadata holds details about calls to the GetMetadata method.
		GetMetadata []struct {
			// Request is the request argument value.
			Request *sarama.MetadataRequest
		}
		// Open holds details about calls to the Open method.
		Open []struct {
			// Conf is the conf argument value.
			Conf *sarama.Config
		}
	}
}

// Addr calls AddrFunc.
func (mock *SaramaBrokerMock) Addr() string {
	if mock.AddrFunc == nil {
		panic("SaramaBrokerMock.AddrFunc: method is nil but SaramaBroker.Addr was just called")
	}
	callInfo := struct {
	}{}
	lockSaramaBrokerMockAddr.Lock()
	mock.calls.Addr = append(mock.calls.Addr, callInfo)
	lockSaramaBrokerMockAddr.Unlock()
	return mock.AddrFunc()
}

// AddrCalls gets all the calls that were made to Addr.
// Check the length with:
//     len(mockedSaramaBroker.AddrCalls())
func (mock *SaramaBrokerMock) AddrCalls() []struct {
} {
	var calls []struct {
	}
	lockSaramaBrokerMockAddr.RLock()
	calls = mock.calls.Addr
	lockSaramaBrokerMockAddr.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *SaramaBrokerMock) Close() error {
	if mock.CloseFunc == nil {
		panic("SaramaBrokerMock.CloseFunc: method is nil but SaramaBroker.Close was just called")
	}
	callInfo := struct {
	}{}
	lockSaramaBrokerMockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	lockSaramaBrokerMockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedSaramaBroker.CloseCalls())
func (mock *SaramaBrokerMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	lockSaramaBrokerMockClose.RLock()
	calls = mock.calls.Close
	lockSaramaBrokerMockClose.RUnlock()
	return calls
}

// Connected calls ConnectedFunc.
func (mock *SaramaBrokerMock) Connected() (bool, error) {
	if mock.ConnectedFunc == nil {
		panic("SaramaBrokerMock.ConnectedFunc: method is nil but SaramaBroker.Connected was just called")
	}
	callInfo := struct {
	}{}
	lockSaramaBrokerMockConnected.Lock()
	mock.calls.Connected = append(mock.calls.Connected, callInfo)
	lockSaramaBrokerMockConnected.Unlock()
	return mock.ConnectedFunc()
}

// ConnectedCalls gets all the calls that were made to Connected.
// Check the length with:
//     len(mockedSaramaBroker.ConnectedCalls())
func (mock *SaramaBrokerMock) ConnectedCalls() []struct {
} {
	var calls []struct {
	}
	lockSaramaBrokerMockConnected.RLock()
	calls = mock.calls.Connected
	lockSaramaBrokerMockConnected.RUnlock()
	return calls
}

// GetMetadata calls GetMetadataFunc.
func (mock *SaramaBrokerMock) GetMetadata(request *sarama.MetadataRequest) (*sarama.MetadataResponse, error) {
	if mock.GetMetadataFunc == nil {
		panic("SaramaBrokerMock.GetMetadataFunc: method is nil but SaramaBroker.GetMetadata was just called")
	}
	callInfo := struct {
		Request *sarama.MetadataRequest
	}{
		Request: request,
	}
	lockSaramaBrokerMockGetMetadata.Lock()
	mock.calls.GetMetadata = append(mock.calls.GetMetadata, callInfo)
	lockSaramaBrokerMockGetMetadata.Unlock()
	return mock.GetMetadataFunc(request)
}

// GetMetadataCalls gets all the calls that were made to GetMetadata.
// Check the length with:
//     len(mockedSaramaBroker.GetMetadataCalls())
func (mock *SaramaBrokerMock) GetMetadataCalls() []struct {
	Request *sarama.MetadataRequest
} {
	var calls []struct {
		Request *sarama.MetadataRequest
	}
	lockSaramaBrokerMockGetMetadata.RLock()
	calls = mock.calls.GetMetadata
	lockSaramaBrokerMockGetMetadata.RUnlock()
	return calls
}

// Open calls OpenFunc.
func (mock *SaramaBrokerMock) Open(conf *sarama.Config) error {
	if mock.OpenFunc == nil {
		panic("SaramaBrokerMock.OpenFunc: method is nil but SaramaBroker.Open was just called")
	}
	callInfo := struct {
		Conf *sarama.Config
	}{
		Conf: conf,
	}
	lockSaramaBrokerMockOpen.Lock()
	mock.calls.Open = append(mock.calls.Open, callInfo)
	lockSaramaBrokerMockOpen.Unlock()
	return mock.OpenFunc(conf)
}

// OpenCalls gets all the calls that were made to Open.
// Check the length with:
//     len(mockedSaramaBroker.OpenCalls())
func (mock *SaramaBrokerMock) OpenCalls() []struct {
	Conf *sarama.Config
} {
	var calls []struct {
		Conf *sarama.Config
	}
	lockSaramaBrokerMockOpen.RLock()
	calls = mock.calls.Open
	lockSaramaBrokerMockOpen.RUnlock()
	return calls
}
