version: "2"
run:
  concurrency: 4
linters:
  default: none
  enable:
    - depguard
    - dogsled
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - nakedret
    - prealloc
    - revive
    - unconvert
    - whitespace
  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    depguard:
      rules:
        avro-wrapper:
          files:
            - ^avro/.*$
          allow:
            - github.com/go-avro/avro
            - .
        main:
          files:
            - ^(?!avro/).*$   # all paths not starting with avro/
          deny:
            - pkg: github.com/go-avro/avro
              desc: "Use github.com/ONSdigital/dp-kafka/v5/avro wrapper instead."
    dupl:
      threshold: 100
    gocognit:
      min-complexity: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - wrapperFunc
        - dupImport
        - ifElseChain
        - octalLiteral
        - hugeParam
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 20
    lll:
      line-length: 140
    misspell:
      locale: UK
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - govet
          - ineffassign
          - revive
        path: _test\.go
issues:
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
